# Generated by Django 4.1.3 on 2022-11-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(choices=[('S', 'Soft Cover'), ('H', 'Hard Cover'), ('E', 'Electronic Copy'), ('A', 'Audio Book')], default='S', max_length=1),
        ),
    ]
