# Generated by Django 4.1.3 on 2022-11-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(to='main_app.subject'),
        ),
    ]
