# Generated by Django 4.1.3 on 2022-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
